export enum TodoActionType {
  ADD_TODO = "ADD_TODO",
  UPDATE_TODO = "UPDATE_TODO",
  DELETE_TODO = "DELETE_TODO",
  OPEN_ADD_TODO_MODAL = "OPEN_ADD_TODO_MODAL",
  OPEN_UPDATE_TODO_MODAL = "OPEN_UPDATE_TODO_MODAL",
  CLOSE_TODO_MODAL = "CLOSE_TODO_MODAL",
}
